# Generated by Django 4.1.7 on 2023-02-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factories',
            old_name='facory_name',
            new_name='factory_name',
        ),
    ]
