# Generated by Django 4.1.7 on 2023-02-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factoryapp', '0002_rename_facory_name_factories_factory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(max_length=50)),
                ('factory_number', models.CharField(max_length=11, unique=True)),
                ('factory_address', models.CharField(max_length=100)),
                ('ceo_name', models.CharField(max_length=100)),
                ('business_number', models.CharField(max_length=10)),
                ('business_registration_file', models.ImageField(upload_to='media')),
            ],
        ),
    ]
