# Generated by Django 4.1.7 on 2023-02-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factoryapp', '0003_factory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factories',
        ),
        migrations.AlterField(
            model_name='factory',
            name='business_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='business_registration_file',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='factory_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
